// ⚠️ AUTO-GENERATED by scripts/gen-personas.mjs —— 唔好手改。改 persona 請改腳本再 `npm run gen:personas`。
export type PersonaGender = 'male' | 'female'
export type PersonaAge = 'young' | 'mid' | 'senior'
export interface PersonaMeta {
  id: string
  gender: PersonaGender
  age: PersonaAge
}

/** 全部教師 persona（中繼資料；SVG 喺 public/personas/<id>.svg）。 */
export const PERSONAS: readonly PersonaMeta[] = [
  { id: 'm-01', gender: 'male', age: 'young' },
  { id: 'm-02', gender: 'male', age: 'young' },
  { id: 'm-03', gender: 'male', age: 'mid' },
  { id: 'm-04', gender: 'male', age: 'mid' },
  { id: 'm-05', gender: 'male', age: 'mid' },
  { id: 'm-06', gender: 'male', age: 'senior' },
  { id: 'm-07', gender: 'male', age: 'senior' },
  { id: 'm-08', gender: 'male', age: 'young' },
  { id: 'm-09', gender: 'male', age: 'mid' },
  { id: 'm-10', gender: 'male', age: 'young' },
  { id: 'f-01', gender: 'female', age: 'young' },
  { id: 'f-02', gender: 'female', age: 'young' },
  { id: 'f-03', gender: 'female', age: 'mid' },
  { id: 'f-04', gender: 'female', age: 'mid' },
  { id: 'f-05', gender: 'female', age: 'mid' },
  { id: 'f-06', gender: 'female', age: 'senior' },
  { id: 'f-07', gender: 'female', age: 'senior' },
  { id: 'f-08', gender: 'female', age: 'young' },
  { id: 'f-09', gender: 'female', age: 'mid' },
  { id: 'f-10', gender: 'female', age: 'young' },
]
