import type { CommunityProfile, CommunityResource } from '../../../lib/community'

// ============================================================
//  資源分享區 — demo 資料
//  ------------------------------------------------------------
//  未接 Supabase（本機 / preview）時用，令個設計 render 到。
//  接咗雲端就用真資料（listResources）。
// ============================================================

const P = {
  chan: {
    id: 'demo-chan',
    displayName: '陳老師',
    school: '聖文德書院',
    showSchool: true,
    anonymous: false,
    avatarColor: '4F46E5',
    bio: '教 BAFS 同經濟十年，鍾意整 gamified 教材。',
    subjects: ['bafs', 'econ'],
  } satisfies CommunityProfile,
  wong: {
    id: 'demo-wong',
    displayName: '黃Miss',
    school: null,
    showSchool: false,
    anonymous: false,
    avatarColor: '0D9488',
    bio: null,
    subjects: ['chin'],
  } satisfies CommunityProfile,
  anon: {
    id: 'demo-anon',
    displayName: '李老師',
    school: '英華女學校',
    showSchool: true,
    anonymous: true,
    avatarColor: 'B45309',
    bio: null,
    subjects: ['math'],
  } satisfies CommunityProfile,
}

function r(over: Partial<CommunityResource> & Pick<CommunityResource, 'id' | 'title' | 'type'>): CommunityResource {
  return {
    ownerId: 'demo-chan',
    description: null,
    subjectPackId: null,
    topicId: null,
    grade: null,
    tags: [],
    filePath: null,
    fileName: null,
    fileMime: null,
    fileSize: null,
    externalUrl: null,
    license: 'original',
    status: 'published',
    downloadCount: 0,
    saveCount: 0,
    ratingSum: 0,
    ratingCount: 0,
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
    ...over,
  }
}

export const DEMO_RESOURCES: CommunityResource[] = [
  r({
    id: 'd1',
    title: '供求曲線互動工作紙（連答案）',
    description: '由淺入深 12 題，每題附情境；最後一頁係老師版答案同批改重點。',
    type: 'handout',
    subjectPackId: 'econ',
    grade: '中四',
    tags: ['供求', '市場', '工作紙'],
    filePath: 'demo/d1.pdf',
    fileName: '供求曲線工作紙.pdf',
    fileMime: 'application/pdf',
    fileSize: 1_840_000,
    license: 'original',
    downloadCount: 342,
    saveCount: 88,
    ratingSum: 56,
    ratingCount: 13,
    createdAt: '2026-06-09T00:00:00Z',
    owner: P.chan,
  }),
  r({
    id: 'd2',
    title: '會計等式入門簡報（雙語）',
    description: '資產 = 負債 + 資本，用真實交易逐步拆解，啱 DSE 改革新課程。',
    type: 'slides',
    subjectPackId: 'bafs',
    grade: '中四',
    tags: ['會計等式', 'BAFS', '雙語'],
    filePath: 'demo/d2.pptx',
    fileName: 'accounting-equation.pptx',
    fileMime: 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    fileSize: 4_200_000,
    downloadCount: 211,
    saveCount: 64,
    ratingSum: 24,
    ratingCount: 5,
    createdAt: '2026-06-07T00:00:00Z',
    owner: P.chan,
  }),
  r({
    id: 'd3',
    title: '中文卷二議論文範文 + 評分示例',
    description: '三篇不同等級範文，附 5** / 5 / 4 拆解，俾學生睇得失。',
    type: 'paper',
    subjectPackId: 'chin',
    grade: '中六',
    tags: ['議論文', '範文', '卷二'],
    filePath: 'demo/d3.pdf',
    fileName: '議論文範文.pdf',
    fileMime: 'application/pdf',
    fileSize: 980_000,
    ownerId: 'demo-wong',
    downloadCount: 503,
    saveCount: 156,
    ratingSum: 92,
    ratingCount: 20,
    createdAt: '2026-06-05T00:00:00Z',
    owner: P.wong,
  }),
  r({
    id: 'd4',
    title: 'YouTube：10 分鐘搞掂機會成本',
    description: '自製動畫短片，課堂引入或翻轉教室都啱。',
    type: 'video',
    subjectPackId: 'econ',
    grade: '中四',
    tags: ['機會成本', '短片'],
    externalUrl: 'https://youtube.com/watch?v=demo',
    license: 'shareable',
    downloadCount: 0,
    saveCount: 41,
    ratingSum: 19,
    ratingCount: 4,
    createdAt: '2026-06-03T00:00:00Z',
    owner: P.chan,
  }),
  r({
    id: 'd5',
    title: '二次函數圖像探究（GeoGebra 連結）',
    description: '學生拖 slider 觀察 a/b/c 點影響拋物線，附引導問題。',
    type: 'link',
    subjectPackId: 'math',
    grade: '中四',
    tags: ['二次函數', 'GeoGebra'],
    externalUrl: 'https://geogebra.org/demo',
    ownerId: 'demo-anon',
    downloadCount: 0,
    saveCount: 73,
    ratingSum: 40,
    ratingCount: 9,
    createdAt: '2026-06-02T00:00:00Z',
    owner: P.anon,
  }),
  r({
    id: 'd6',
    title: '通識／公民：專題研習備忘筆記',
    description: '由選題到匯報嘅 checklist，學生人手一份唔會甩漏。',
    type: 'note',
    subjectPackId: 'ls',
    grade: '中五',
    tags: ['專題研習', 'IES'],
    filePath: 'demo/d6.pdf',
    fileName: 'ies-checklist.pdf',
    fileMime: 'application/pdf',
    fileSize: 320_000,
    ownerId: 'demo-wong',
    downloadCount: 128,
    saveCount: 52,
    ratingSum: 14,
    ratingCount: 3,
    createdAt: '2026-05-30T00:00:00Z',
    owner: P.wong,
  }),
]
